// import type { NextPage } from "next";
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";

import * as cheerio from "cheerio";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";

export async function getStaticProps() {
  const res = await fetch("https://japari-library.com/wiki/List_of_Friends");
  const resString = await res.text();
  const $ = cheerio.load(resString);
  // let testArray: string[];
  const test = $("img")
    .parent()
    .each(function (i, element) {
      console.log($(this).attr("title"));
      // let x = $(this).attr("title");
      // testArray.push(x);
    });
  return {
    props: { test },
  };

  // https://dev.to/caelinsutch/building-a-web-scraper-in-typescript-14l1

  // https://stackoverflow.com/questions/50429215/pulling-multiple-values-from-the-same-tr-with-cheerio

  // const res = await fetch("https://japari-library.com/wiki/List_of_Friends");
  // const resString = await res.text();
  // const $ = cheerio.load(resString);
  // const test = $("td a").text();
  // const testArray = test.split(" ");
  // console.log(test);
  // console.log(typeof test);
  // console.log(testArray);
  // console.log(typeof testArray);
  // return {
  //   props: { test },
  // };

  // const res = await fetch(
  //   "https://japari-library.com/wiki/File:Forest_OwletOriginal.jpg"
  // );
  // const dataString = await res.text();
  // const $ = cheerio.load(dataString);
  // const link = $(".internal").attr("href");
  // const title = $(".internal").attr("title");
  // return {
  //   props: { link, title },
  // };
}

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>KF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image
          src="https://japari-library.com/w/images/d/d4/Hi-no-ToriOriginal.jpg"
          width={455}
          height={600}
          alt="African_Rock_PythonOriginal"
        />
      </div>
      {/* <div>
        <Image
          src={"https://japari-library.com/" + props.link}
          width={200}
          height={400}
          alt={props.title}
        />
      </div> */}
    </>
  );
};

export default Home;

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{" "}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{" "}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   );
// };

// export default Home;
